# Generated by Django 2.2.4 on 2019-08-02 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20190731_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='productowners',
            name='shared_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='product.Product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productowners',
            unique_together={('shareholder', 'shared_object')},
        ),
        migrations.RemoveField(
            model_name='productowners',
            name='object',
        ),
    ]
