# Generated by Django 2.2.3 on 2019-07-31 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tech_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatentOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patent.Patent')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
